name: GitHub Page

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: https://registry.npmjs.org
    - run: yarn install
    - name: Generate
      env:
        BASE_URL: 'https://feryardiant.id/nuxt-appendchild/'
      run: yarn generate
    - name: Deploy
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
